import unittest

# Import the function that we are going to test.
from log_parser import parse_log_line


class TestLogParser(unittest.TestCase):

    # Test that a valid log line is parsed correctly.
    def test_parse_log_line(self):
        # This is a sample log entry similar to the entries
        # generated by our main.py program.
        log_line = '198.51.100.7 - - [28/Sep/2026:22:30:51 +0200] "GET /about HTTP/1.1" 401 3734'

        # Send the log line to the parser.
        result = parse_log_line(log_line)

        # Check that each part of the log was extracted correctly.
        self.assertEqual(result["ip"], "198.51.100.7")
        self.assertEqual(result["method"], "GET")
        self.assertEqual(result["path"], "/about")
        self.assertEqual(result["status"], 401)
        self.assertEqual(result["size"], 3734)


# Run the tests when this file is executed directly.
if __name__ == "__main__":
    unittest.main()
